{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "a4159bbc-31ba-4791-8192-427580eac026",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Tüm işlemler tamamlandı. Ödev için gerekli 6 çıktı dosyası başarıyla üretilmiştir.\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from scipy import stats\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.metrics import f1_score, precision_score, recall_score, classification_report\n",
    "from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler\n",
    "from sklearn.compose import ColumnTransformer\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.decomposition import PCA\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# --- 1. Veri Yükleme ve Temizleme ---\n",
    "file_name = \"Expanded_data_with_more_features (2).csv\"\n",
    "df = pd.read_csv(file_name)\n",
    "df = df.drop('Unnamed: 0', axis=1)\n",
    "\n",
    "# Eksik değerleri doldur\n",
    "categorical_cols = df.select_dtypes(include='object').columns.tolist()\n",
    "for col in categorical_cols:\n",
    "    df[col] = df[col].fillna(df[col].mode()[0])\n",
    "df['NrSiblings'] = df['NrSiblings'].fillna(df['NrSiblings'].median()).astype(int)\n",
    "df['AverageScore'] = df[['MathScore', 'ReadingScore', 'WritingScore']].mean(axis=1)\n",
    "\n",
    "# Temizlenmiş veriyi kaydet (ÇIKTI 1)\n",
    "df.to_csv('cleaned_data.csv', index=False)\n",
    "\n",
    "# Hedef Sınıflandırma\n",
    "threshold = df['AverageScore'].quantile(0.75)\n",
    "df['High_Performance'] = (df['AverageScore'] >= threshold).astype(int)\n",
    "\n",
    "score_cols = ['MathScore', 'ReadingScore', 'WritingScore', 'AverageScore']\n",
    "Y = df['High_Performance']\n",
    "X_full = df.drop(columns=score_cols + ['High_Performance'])\n",
    "\n",
    "# Kategorik Encoding Tanımları\n",
    "ordinal_features = ['WklyStudyHours']\n",
    "nominal_features = [col for col in X_full.select_dtypes(include='object').columns if col not in ordinal_features]\n",
    "numerical_features = X_full.select_dtypes(include=np.number).columns.tolist()\n",
    "wkly_study_hours_order = ['< 5', '5 - 10', '> 10']\n",
    "\n",
    "\n",
    "# --- 2. İstatistiksel Etki Analizi (ANOVA/Korelasyon) ---\n",
    "scores = ['MathScore', 'ReadingScore', 'WritingScore', 'AverageScore']\n",
    "anova_features = X_full.select_dtypes(include='object').columns.tolist()\n",
    "corr_features = X_full.select_dtypes(include=np.number).columns.tolist()\n",
    "results_list = []\n",
    "\n",
    "for feature in anova_features:\n",
    "    for score in scores:\n",
    "        groups = [df[df[feature] == category][score].dropna() for category in df[feature].unique()]\n",
    "        if len(groups) > 1:\n",
    "            f_statistic, p_value = stats.f_oneway(*groups)\n",
    "            results_list.append({'Feature': feature, 'Target': score, 'Test': 'ANOVA', 'p-value': p_value, 'Correlation': np.nan})\n",
    "\n",
    "for feature in corr_features:\n",
    "    for score in scores:\n",
    "        corr, p_value = stats.pearsonr(df[feature], df[score])\n",
    "        results_list.append({'Feature': feature, 'Target': score, 'Test': 'Pearson Correlation', 'p-value': p_value, 'Correlation': corr})\n",
    "\n",
    "summary_df = pd.DataFrame(results_list)\n",
    "summary_df['Significant Effect'] = summary_df['p-value'] < 0.05\n",
    "summary_df = summary_df.sort_values(by=['Target', 'p-value']).reset_index(drop=True)\n",
    "\n",
    "# Rapor için sonuç tablosunu kaydet (ÇIKTI 2)\n",
    "report_df = summary_df[['Target', 'Feature', 'Test', 'p-value', 'Correlation', 'Significant Effect']].copy()\n",
    "report_df['p-value'] = report_df['p-value'].apply(lambda x: f\"{x:.3e}\" if not pd.isna(x) else \"\")\n",
    "report_df['Correlation'] = report_df['Correlation'].apply(lambda x: f\"{x:.3f}\" if not pd.isna(x) else \"\")\n",
    "report_df.to_csv('feature_impact_summary.csv', index=False)\n",
    "\n",
    "\n",
    "# --- 3. Modellerin Kurulumu ve Karşılaştırılması ---\n",
    "def evaluate_model(model, X_test, Y_test, name):\n",
    "    Y_pred = model.predict(X_test)\n",
    "    precision = precision_score(Y_test, Y_pred, average='binary')\n",
    "    recall = recall_score(Y_test, Y_pred, average='binary')\n",
    "    f1 = f1_score(Y_test, Y_pred, average='binary')\n",
    "    return {'Method': name, 'F1-Score': f1, 'Precision': precision, 'Recall': recall, 'Model': model, 'X_test': X_test, 'Y_test': Y_test}\n",
    "\n",
    "# MODEL 1: FEATURE SELECTION (FS)\n",
    "features_to_drop_fs = ['ParentMaritalStatus', 'TransportMeans', 'NrSiblings']\n",
    "X_fs = X_full.drop(columns=features_to_drop_fs)\n",
    "nominal_fs = [col for col in nominal_features if col not in features_to_drop_fs]\n",
    "numerical_fs = [col for col in numerical_features if col not in features_to_drop_fs]\n",
    "\n",
    "preprocessor_fs = ColumnTransformer(\n",
    "    transformers=[\n",
    "        ('ord', OrdinalEncoder(categories=[wkly_study_hours_order]), ordinal_features),\n",
    "        ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False), nominal_fs),\n",
    "        ('num', StandardScaler(), numerical_fs) \n",
    "    ],\n",
    "    remainder='drop'\n",
    ")\n",
    "pipeline_fs = Pipeline(steps=[('preprocessor', preprocessor_fs), ('classifier', RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced'))])\n",
    "X_train_fs, X_test_fs, Y_train, Y_test = train_test_split(X_fs, Y, test_size=0.3, random_state=42, stratify=Y)\n",
    "pipeline_fs.fit(X_train_fs, Y_train)\n",
    "results_fs = evaluate_model(pipeline_fs, X_test_fs, Y_test, \"Feature Selection (FS)\")\n",
    "\n",
    "# MODEL 2: PCA (FEATURE EXTRACTION)\n",
    "preprocessor_pca = ColumnTransformer(\n",
    "    transformers=[\n",
    "        ('ord', OrdinalEncoder(categories=[wkly_study_hours_order]), ordinal_features),\n",
    "        ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False), nominal_features),\n",
    "        ('num', StandardScaler(), numerical_features)\n",
    "    ],\n",
    "    remainder='drop'\n",
    ")\n",
    "pipeline_pca = Pipeline(steps=[\n",
    "    ('preprocessor', preprocessor_pca),\n",
    "    ('pca', PCA(n_components=0.95, random_state=42)),\n",
    "    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced'))\n",
    "])\n",
    "X_train_pca, X_test_pca, Y_train, Y_test = train_test_split(X_full, Y, test_size=0.3, random_state=42, stratify=Y)\n",
    "pipeline_pca.fit(X_train_pca, Y_train)\n",
    "results_pca = evaluate_model(pipeline_pca, X_test_pca, Y_test, \"PCA (Feature Extraction)\")\n",
    "\n",
    "# Sonuçların Karşılaştırılması\n",
    "comparison_df = pd.DataFrame([results_fs, results_pca])\n",
    "comparison_df = comparison_df.sort_values(by='F1-Score', ascending=False).reset_index(drop=True)\n",
    "\n",
    "# Karşılaştırma tablosunu kaydet\n",
    "comparison_df[['Method', 'F1-Score', 'Precision', 'Recall']].to_csv('model_comparison_metrics.csv', index=False)\n",
    "\n",
    "# --- 4. En İyi Modelin Detaylı Raporlaması ---\n",
    "# Feature Selection (FS) modeli, en yüksek F1-Score'a sahip olduğu için en iyi model kabul edilir.\n",
    "best_model_results = results_fs\n",
    "best_model_pipeline = best_model_results['Model']\n",
    "Y_pred_best = best_model_pipeline.predict(best_model_results['X_test'])\n",
    "\n",
    "# Classification Report'u kaydet \n",
    "report = classification_report(best_model_results['Y_test'], Y_pred_best, target_names=['Normal Performance (0)', 'High Performance (1)'])\n",
    "with open('classification_report.txt', 'w') as f:\n",
    "    f.write(report)\n",
    "\n",
    "# Feature Importance Çıktıları\n",
    "classifier = best_model_pipeline.named_steps['classifier']\n",
    "preprocessor = best_model_pipeline.named_steps['preprocessor']\n",
    "\n",
    "# OHE sonrası feature isimlerini doğru al\n",
    "ohe_feature_names = list(preprocessor.named_transformers_['onehot'].get_feature_names_out(nominal_fs))\n",
    "all_feature_names = ordinal_features + ohe_feature_names + numerical_features\n",
    "\n",
    "# FS'de 3 sütun düşürüldüğü için X_fs'in sütunlarını kullan\n",
    "feature_names_fs = X_test_fs.columns.tolist()\n",
    "\n",
    "processed_feature_names = ordinal_features + nominal_fs\n",
    "# Numerik sütunlar (dropped: NrSiblings) da eklenmeliydi ama FS'de zaten düşürüldü.\n",
    "# Kodun çalıştığı feature isimleri OHE sonrası oluşan toplam 23 sütundur.\n",
    "# Doğru feature isimlerini çıkarım:\n",
    "processed_X_train = preprocessor_fs.transform(X_train_fs)\n",
    "all_feature_names = list(preprocessor_fs.get_feature_names_out())\n",
    "\n",
    "\n",
    "feature_importances = classifier.feature_importances_\n",
    "importance_df = pd.DataFrame({\n",
    "    'Feature': all_feature_names,\n",
    "    'Importance': feature_importances\n",
    "}).sort_values(by='Importance', ascending=False)\n",
    "\n",
    "# Özellik Önemini kaydet\n",
    "importance_df.to_csv('model_feature_importance.csv', index=False)\n",
    "\n",
    "# Grafik oluştur ve kaydet\n",
    "plt.figure(figsize=(12, 8))\n",
    "plt.barh(importance_df['Feature'][:15], importance_df['Importance'][:15], color='darkred') # İlk 15'i gösterelim\n",
    "plt.xlabel('Özellik Önem Derecesi (Gini)')\n",
    "plt.ylabel('Özellik')\n",
    "plt.title('Random Forest Özellik Önem Sıralaması (Feature Selection Modeli)')\n",
    "plt.gca().invert_yaxis()\n",
    "plt.tight_layout()\n",
    "plt.savefig('random_forest_feature_importance.png')\n",
    "plt.close()\n",
    "\n",
    "print(\"Tüm işlemler tamamlandı. Ödev için gerekli 6 çıktı dosyası başarıyla üretilmiştir.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fa48e13f-54fb-4845-8850-01d9c4d8d3ca",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
